[package]
name = "notkaif/motus"
description = "Lightweight animation handler wrapper for Roblox animator objects"
version = "1.0.0"
license = "MIT"
authors = ["Kaif"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
exclude = ["README.md", ".vscode", "rokit.toml"]

[dependencies]
motus = "notkaif/motus@0.1.0"